// --- 1. 完全内蔵データベース ---
const AFRICA_DATA = {
    "DZA": { "name": "Algeria", "gdp": "191.9 Billion USD", "system": "Unitary semi-presidential republic", "stability_index": "Moderate", "risk_analysis": "Reliance on hydrocarbons, youth unemployment." },
    "AGO": { "name": "Angola", "gdp": "106.7 Billion USD", "system": "Unitary presidential republic", "stability_index": "Fragile", "risk_analysis": "Oil dependency, high debt, corruption." },
    "BEN": { "name": "Benin", "gdp": "17.4 Billion USD", "system": "Unitary presidential republic", "stability_index": "Moderate", "risk_analysis": "Spillover violence from Sahel, rising living costs." },
    "BWA": { "name": "Botswana", "gdp": "20.3 Billion USD", "system": "Parliamentary republic", "stability_index": "Stable", "risk_analysis": "Diamond dependency, inequality." },
    "BFA": { "name": "Burkina Faso", "gdp": "18.8 Billion USD", "system": "Military Junta", "stability_index": "Critical", "risk_analysis": "Jihadist insurgency, political instability." },
    "BDI": { "name": "Burundi", "gdp": "3.2 Billion USD", "system": "Presidential republic", "stability_index": "Fragile", "risk_analysis": "Political repression, poverty, ethnic tensions." },
    "CMR": { "name": "Cameroon", "gdp": "44.3 Billion USD", "system": "Presidential republic", "stability_index": "Fragile", "risk_analysis": "Anglophone crisis, Boko Haram in north." },
    "CAF": { "name": "Central African Rep.", "gdp": "2.5 Billion USD", "system": "Semi-presidential republic", "stability_index": "Critical", "risk_analysis": "Armed group violence, weak state authority." },
    "TCD": { "name": "Chad", "gdp": "11.7 Billion USD", "system": "Transitional Military Council", "stability_index": "Critical", "risk_analysis": "Rebel incursions, social unrest, delayed elections." },
    "COD": { "name": "DR Congo", "gdp": "58.0 Billion USD", "system": "Semi-presidential republic", "stability_index": "Critical", "risk_analysis": "Conflict in East (M23, ADF), mining disputes." },
    "COG": { "name": "Rep. of Congo", "gdp": "14.6 Billion USD", "system": "Semi-presidential republic", "stability_index": "Fragile", "risk_analysis": "Debt distress, oil dependency." },
    "CIV": { "name": "Côte d'Ivoire", "gdp": "70.0 Billion USD", "system": "Presidential republic", "stability_index": "Moderate", "risk_analysis": "Northern border security, political succession." },
    "DJI": { "name": "Djibouti", "gdp": "3.5 Billion USD", "system": "Presidential republic", "stability_index": "Moderate", "risk_analysis": "Strategic regional tensions, debt to China." },
    "EGY": { "name": "Egypt", "gdp": "476.7 Billion USD", "system": "Semi-presidential republic", "stability_index": "Moderate", "risk_analysis": "Inflation, currency devaluation, Nile dam dispute." },
    "GNQ": { "name": "Eq. Guinea", "gdp": "11.8 Billion USD", "system": "Presidential republic", "stability_index": "Fragile", "risk_analysis": "Declining oil output, lack of succession plan." },
    "ERI": { "name": "Eritrea", "gdp": "2.6 Billion USD", "system": "One-party presidential republic", "stability_index": "Critical", "risk_analysis": "Totalitarian control, indefinite national service." },
    "ETH": { "name": "Ethiopia", "gdp": "126.8 Billion USD", "system": "Federal parliamentary republic", "stability_index": "Fragile", "risk_analysis": "Post-war recovery (Tigray), Amhara/Oromia insurgencies." },
    "GAB": { "name": "Gabon", "gdp": "21.0 Billion USD", "system": "Transitional Military", "stability_index": "Uncertain", "risk_analysis": "Post-coup transition, oil dependency." },
    "GHA": { "name": "Ghana", "gdp": "72.8 Billion USD", "system": "Presidential republic", "stability_index": "Stable", "risk_analysis": "Debt crisis, inflation, spillover from Sahel." },
    "GIN": { "name": "Guinea", "gdp": "21.2 Billion USD", "system": "Military Junta", "stability_index": "Fragile", "risk_analysis": "Transition delays, mining sector stability." },
    "KEN": { "name": "Kenya", "gdp": "113.4 Billion USD", "system": "Presidential republic", "stability_index": "Stable", "risk_analysis": "Cost of living protests, tax hikes, drought." },
    "LBR": { "name": "Liberia", "gdp": "4.0 Billion USD", "system": "Presidential republic", "stability_index": "Moderate", "risk_analysis": "Corruption, weak infrastructure." },
    "LBY": { "name": "Libya", "gdp": "45.7 Billion USD", "system": "Provisional Government", "stability_index": "Critical", "risk_analysis": "East-West political divide, militia control." },
    "MDG": { "name": "Madagascar", "gdp": "15.0 Billion USD", "system": "Semi-presidential republic", "stability_index": "Fragile", "risk_analysis": "Climate disasters, poverty." },
    "MLI": { "name": "Mali", "gdp": "18.8 Billion USD", "system": "Military Junta", "stability_index": "Critical", "risk_analysis": "Jihadist expansion, withdrawal of UN forces." },
    "MAR": { "name": "Morocco", "gdp": "134.1 Billion USD", "system": "Constitutional monarchy", "stability_index": "Stable", "risk_analysis": "Western Sahara conflict, earthquake recovery." },
    "MOZ": { "name": "Mozambique", "gdp": "17.8 Billion USD", "system": "Semi-presidential republic", "stability_index": "Fragile", "risk_analysis": "Insurgency in Cabo Delgado (gas projects)." },
    "NAM": { "name": "Namibia", "gdp": "12.6 Billion USD", "system": "Semi-presidential republic", "stability_index": "Stable", "risk_analysis": "High inequality, youth unemployment." },
    "NER": { "name": "Niger", "gdp": "13.9 Billion USD", "system": "Military Junta", "stability_index": "Critical", "risk_analysis": "Post-coup sanctions, jihadist attacks." },
    "NGA": { "name": "Nigeria", "gdp": "477.4 Billion USD", "system": "Federal presidential republic", "stability_index": "Fragile", "risk_analysis": "Boko Haram, banditry, inflation, oil theft." },
    "RWA": { "name": "Rwanda", "gdp": "13.3 Billion USD", "system": "Presidential republic", "stability_index": "Stable", "risk_analysis": "Tensions with DRC, suppression of dissent." },
    "SEN": { "name": "Senegal", "gdp": "27.6 Billion USD", "system": "Presidential republic", "stability_index": "Moderate", "risk_analysis": "Recent political unrest, youth unemployment." },
    "SLE": { "name": "Sierra Leone", "gdp": "4.0 Billion USD", "system": "Presidential republic", "stability_index": "Fragile", "risk_analysis": "Post-election tensions, inflation." },
    "SOM": { "name": "Somalia", "gdp": "8.1 Billion USD", "system": "Federal parliamentary republic", "stability_index": "Critical", "risk_analysis": "Al-Shabaab insurgency, recurring famine." },
    "ZAF": { "name": "South Africa", "gdp": "405.9 Billion USD", "system": "Parliamentary republic", "stability_index": "Moderate", "risk_analysis": "Energy crisis, high crime, unemployment." },
    "SSD": { "name": "South Sudan", "gdp": "12.0 Billion USD", "system": "Federal transitional republic", "stability_index": "Critical", "risk_analysis": "Inter-communal violence, delayed elections." },
    "SDN": { "name": "Sudan", "gdp": "51.6 Billion USD", "system": "Military Junta (War)", "stability_index": "Critical", "risk_analysis": "Civil war (SAF vs RSF), humanitarian catastrophe." },
    "TZA": { "name": "Tanzania", "gdp": "75.7 Billion USD", "system": "Presidential republic", "stability_index": "Stable", "risk_analysis": "Political reconciliation process, infrastructure debt." },
    "TGO": { "name": "Togo", "gdp": "8.1 Billion USD", "system": "Presidential republic", "stability_index": "Moderate", "risk_analysis": "Dynastic rule concerns, northern security." },
    "TUN": { "name": "Tunisia", "gdp": "46.6 Billion USD", "system": "Presidential republic", "stability_index": "Fragile", "risk_analysis": "Democratic backsliding, economic crisis." },
    "UGA": { "name": "Uganda", "gdp": "45.5 Billion USD", "system": "Presidential republic", "stability_index": "Moderate", "risk_analysis": "Long-standing rule, corruption, ADF attacks." },
    "ZMB": { "name": "Zambia", "gdp": "29.7 Billion USD", "system": "Presidential republic", "stability_index": "Stable", "risk_analysis": "Debt restructuring, copper price volatility." },
    "ZWE": { "name": "Zimbabwe", "gdp": "20.6 Billion USD", "system": "Presidential republic", "stability_index": "Fragile", "risk_analysis": "Hyperinflation, political repression." }
};

// --- 2. 名前揺らぎ吸収用エイリアス辞書 ---
const COUNTRY_ALIASES = {
    "Dem. Rep. Congo": "COD",
    "Democratic Republic of the Congo": "COD",
    "S. Sudan": "SSD",
    "South Sudan": "SSD",
    "Eq. Guinea": "GNQ",
    "Equatorial Guinea": "GNQ",
    "Central African Rep.": "CAF",
    "Central African Republic": "CAF",
    "Côte d'Ivoire": "CIV",
    "Ivory Coast": "CIV",
    "Cote d'Ivoire": "CIV",
    "eSwatini": "SWZ",
    "Swaziland": "SWZ",
    "Rep. of Congo": "COG",
    "Republic of the Congo": "COG",
    "Congo": "COG",
    "W. Sahara": "MAR",
    "Western Sahara": "MAR",
    "Somaliland": "SOM",
    "Tanzania": "TZA",
    "United Republic of Tanzania": "TZA"
};
