// --- AUTO-GENERATED BY CHATGPT & GITHUB ACTIONS (2026-02-10 16:08:29) ---
const AFRICA_DATA = {
    "DZA": {
        "name": "Algeria",
        "gdp": "191.9 Billion USD",
        "system": "Unitary semi-presidential republic",
        "risk_analysis": "[2026-02-10] Protests over unemployment and political stasis challenge government stability.",
        "stability_index": "Moderate"
    },
    "AGO": {
        "name": "Angola",
        "gdp": "106.7 Billion USD",
        "system": "Unitary presidential republic",
        "risk_analysis": "[2026-02-10] Economic instability due to volatile oil prices and fiscal mismanagement.",
        "stability_index": "Fragile"
    },
    "BEN": {
        "name": "Benin",
        "gdp": "17.4 Billion USD",
        "system": "Unitary presidential republic",
        "risk_analysis": "[2026-02-10] Border tensions with Burkina Faso over security threats.",
        "stability_index": "Moderate"
    },
    "BWA": {
        "name": "Botswana",
        "gdp": "20.3 Billion USD",
        "system": "Parliamentary republic",
        "risk_analysis": "[2026-02-10] Potential water shortages impacting regional relations and agriculture.",
        "stability_index": "Stable"
    },
    "BFA": {
        "name": "Burkina Faso",
        "gdp": "18.8 Billion USD",
        "system": "Military Junta",
        "risk_analysis": "[2026-02-10] Jihadist attacks in the northern region increase displacements.",
        "stability_index": "Critical"
    },
    "BDI": {
        "name": "Burundi",
        "gdp": "3.2 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Political unrest post-election exacerbates ethnic tensions.",
        "stability_index": "Fragile"
    },
    "CMR": {
        "name": "Cameroon",
        "gdp": "44.3 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Anglophone regions experience separatist violence with increased military presence.",
        "stability_index": "Fragile"
    },
    "CAF": {
        "name": "Central African Rep.",
        "gdp": "2.5 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] Ongoing rebel activities destabilize central governance.",
        "stability_index": "Critical"
    },
    "TCD": {
        "name": "Chad",
        "gdp": "11.7 Billion USD",
        "system": "Transitional Military Council",
        "risk_analysis": "[2026-02-10] Inter-ethnic clashes escalate in southern provinces.",
        "stability_index": "Fragile"
    },
    "COD": {
        "name": "DR Congo",
        "gdp": "58.0 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] M23 rebel resurgence in eastern provinces threatens regional security.",
        "stability_index": "Critical"
    },
    "COG": {
        "name": "Rep. of Congo",
        "gdp": "14.6 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] Economic contraction triggers civil unrest as poverty rates climb.",
        "stability_index": "Fragile"
    },
    "CIV": {
        "name": "C\u00f4te d'Ivoire",
        "gdp": "70.0 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Political tensions rise ahead of upcoming elections amid economic concerns.",
        "stability_index": "Moderate"
    },
    "DJI": {
        "name": "Djibouti",
        "gdp": "3.5 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Regional maritime security concerns due to piracy threats.",
        "stability_index": "Moderate"
    },
    "EGY": {
        "name": "Egypt",
        "gdp": "476.7 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] Sinai Peninsula insurgency and political crackdowns on dissent.",
        "stability_index": "Fragile"
    },
    "GNQ": {
        "name": "Eq. Guinea",
        "gdp": "11.8 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Corruption and inequality spark small-scale protests in urban areas.",
        "stability_index": "Fragile"
    },
    "ERI": {
        "name": "Eritrea",
        "gdp": "2.6 Billion USD",
        "system": "One-party presidential republic",
        "risk_analysis": "[2026-02-10] High militarization and indefinite national service fuel refugee exodus.",
        "stability_index": "Critical"
    },
    "ETH": {
        "name": "Ethiopia",
        "gdp": "126.8 Billion USD",
        "system": "Federal parliamentary republic",
        "risk_analysis": "[2026-02-10] Ethnic tensions and border disputes post-Tigray conflict unresolved.",
        "stability_index": "Fragile"
    },
    "GAB": {
        "name": "Gabon",
        "gdp": "21.0 Billion USD",
        "system": "Transitional Military",
        "risk_analysis": "[2026-02-10] Economic woes and opposition pressures increase post-election stability risks.",
        "stability_index": "Moderate"
    },
    "GHA": {
        "name": "Ghana",
        "gdp": "72.8 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Economic performance threatened by debt and power supply issues.",
        "stability_index": "Stable"
    },
    "GIN": {
        "name": "Guinea",
        "gdp": "21.2 Billion USD",
        "system": "Military Junta",
        "risk_analysis": "[2026-02-10] Unrest over mining industry exploitation and revenue distribution.",
        "stability_index": "Fragile"
    },
    "KEN": {
        "name": "Kenya",
        "gdp": "113.4 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Tensions on Somali border due to al-Shabaab activities and intercommunal violence.",
        "stability_index": "Moderate"
    },
    "LBR": {
        "name": "Liberia",
        "gdp": "4.0 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Socioeconomic disparities and land disputes challenge community cohesion.",
        "stability_index": "Fragile"
    },
    "LBY": {
        "name": "Libya",
        "gdp": "45.7 Billion USD",
        "system": "Provisional Government",
        "risk_analysis": "[2026-02-10] Militia clashes and fragmented government undermine national unity.",
        "stability_index": "Critical"
    },
    "MDG": {
        "name": "Madagascar",
        "gdp": "15.0 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] Cyclone impacts worsen food insecurity and economic vulnerability.",
        "stability_index": "Fragile"
    },
    "MLI": {
        "name": "Mali",
        "gdp": "18.8 Billion USD",
        "system": "Military Junta",
        "risk_analysis": "[2026-02-10] Extremism in the north threatens regional security efforts.",
        "stability_index": "Critical"
    },
    "MAR": {
        "name": "Morocco",
        "gdp": "134.1 Billion USD",
        "system": "Constitutional monarchy",
        "risk_analysis": "[2026-02-10] Western Sahara tensions remain unresolved amid regional power struggles.",
        "stability_index": "Moderate"
    },
    "MOZ": {
        "name": "Mozambique",
        "gdp": "17.8 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] Insurgent activities in Cabo Delgado fuel humanitarian crises.",
        "stability_index": "Fragile"
    },
    "NAM": {
        "name": "Namibia",
        "gdp": "12.6 Billion USD",
        "system": "Semi-presidential republic",
        "risk_analysis": "[2026-02-10] Severe drought conditions impacting agricultural output and rural livelihoods.",
        "stability_index": "Stable"
    },
    "NER": {
        "name": "Niger",
        "gdp": "13.9 Billion USD",
        "system": "Military Junta",
        "risk_analysis": "[2026-02-10] Cross-border terrorism challenges defense capabilities in isolated areas.",
        "stability_index": "Fragile"
    },
    "NGA": {
        "name": "Nigeria",
        "gdp": "477.4 Billion USD",
        "system": "Federal presidential republic",
        "risk_analysis": "[2026-02-10] Boko Haram insurgency destabilizes northeastern regions and worsens humanitarian conditions.",
        "stability_index": "Fragile"
    },
    "RWA": {
        "name": "Rwanda",
        "gdp": "13.3 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Tensions with DRC over cross-border rebel activities and security intrigues.",
        "stability_index": "Moderate"
    },
    "SEN": {
        "name": "Senegal",
        "gdp": "27.6 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Protests against governance issues and electoral transparency concerns.",
        "stability_index": "Moderate"
    },
    "SLE": {
        "name": "Sierra Leone",
        "gdp": "4.0 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Economic decline and corruption spark public discontent and protests.",
        "stability_index": "Fragile"
    },
    "SOM": {
        "name": "Somalia",
        "gdp": "8.1 Billion USD",
        "system": "Federal parliamentary republic",
        "risk_analysis": "[2026-02-10] Persistent al-Shabaab attacks challenge central government authority.",
        "stability_index": "Critical"
    },
    "ZAF": {
        "name": "South Africa",
        "gdp": "405.9 Billion USD",
        "system": "Parliamentary republic",
        "risk_analysis": "[2026-02-10] Load shedding and unemployment exacerbate socioeconomic disparities.",
        "stability_index": "Moderate"
    },
    "SSD": {
        "name": "South Sudan",
        "gdp": "12.0 Billion USD",
        "system": "Federal transitional republic",
        "risk_analysis": "[2026-02-10] Famine threats amid ongoing civil war and peace deal setbacks.",
        "stability_index": "Critical"
    },
    "SDN": {
        "name": "Sudan",
        "gdp": "51.6 Billion USD",
        "system": "Military Junta (War)",
        "risk_analysis": "[2026-02-10] Military-led government faces protests and economic downturns.",
        "stability_index": "Critical"
    },
    "TZA": {
        "name": "Tanzania",
        "gdp": "75.7 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Minor political unrest over opposition suppression following elections.",
        "stability_index": "Moderate"
    },
    "TGO": {
        "name": "Togo",
        "gdp": "8.1 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Political reform demands grow alongside economic hardships.",
        "stability_index": "Moderate"
    },
    "TUN": {
        "name": "Tunisia",
        "gdp": "46.6 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Political paralysis and economic issues fuel public protests.",
        "stability_index": "Fragile"
    },
    "UGA": {
        "name": "Uganda",
        "gdp": "45.5 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Political repression and human rights concerns heighten international scrutiny.",
        "stability_index": "Moderate"
    },
    "ZMB": {
        "name": "Zambia",
        "gdp": "29.7 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Economic recovery slow due to copper price fluctuations and debt challenges.",
        "stability_index": "Fragile"
    },
    "ZWE": {
        "name": "Zimbabwe",
        "gdp": "20.6 Billion USD",
        "system": "Presidential republic",
        "risk_analysis": "[2026-02-10] Hyperinflation and government crackdowns on dissent stifle recovery prospects.",
        "stability_index": "Critical"
    }
};

const COUNTRY_ALIASES = {
    "Dem. Rep. Congo": "COD",
    "Democratic Republic of the Congo": "COD",
    "S. Sudan": "SSD",
    "South Sudan": "SSD",
    "Eq. Guinea": "GNQ",
    "Equatorial Guinea": "GNQ",
    "Central African Rep.": "CAF",
    "Central African Republic": "CAF",
    "C\u00f4te d'Ivoire": "CIV",
    "Ivory Coast": "CIV",
    "Cote d'Ivoire": "CIV",
    "eSwatini": "SWZ",
    "Swaziland": "SWZ",
    "Rep. of Congo": "COG",
    "Republic of the Congo": "COG",
    "Congo": "COG",
    "W. Sahara": "MAR",
    "Western Sahara": "MAR",
    "Somaliland": "SOM",
    "Tanzania": "TZA",
    "United Republic of Tanzania": "TZA"
};
